[package]
edition = "2021"
name = "jonaskruckenberg"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = {version = "0.4.17", features = ["release_max_level_off"]}
wasm-logger = "0.2.0"
yew = "0.19.3"
yew-router = "0.16.0"

[profile.release]
codegen-units = 1
lto = true
opt-level = 'z'
panic = 'abort'
