[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[build.environment]
  NPM_FLAGS = "--version" # prevent Netlify npm install
[build]
  command = 'npx pnpm install --store=node_modules/.pnpm-store && npm run build'
  publish = 'dist'
