[[plugins]]
package = "netlify-plugin-cache"
  [plugins.inputs]
  paths = ["node_modules/.cache/vite-plugin-imageset"]

[[plugins]]
package = "netlify-plugin-inline-critical-css"
  [plugins.inputs]
    # Whether to minify the generated critical-path CSS.
    minify = true

[[plugins]]
  package = "@netlify/plugin-lighthouse"
 
  # optional, fails build when a category is below a threshold
  [plugins.inputs.thresholds]
    performance = 0.9
    accessibility = 0.9
    best-practices = 0.9
    seo = 0.9
    pwa = 0

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[build]
command = "yarn build"

functions = "/functions"
