[[plugins]]
package = "netlify-plugin-cache"
  [plugins.inputs]
  paths = ["node_modules/.cache/vite-plugin-imageset"]

[[plugins]]
package = "netlify-plugin-inline-critical-css"
  [plugins.inputs]
    # Whether to minify the generated critical-path CSS.
    minify = true

[build]
command = "yarn build"

functions = "/functions"
