[build]
target = "index.html"
dist = "dist"

[tools]
wasm_opt = "version_110"
sass = "1.55.0"

[[hooks]]
# Runs terser on the generated javascript glue-code
stage = "post_build"
command = "bash"
command_arguments = ["-c", "if [[ $TRUNK_PROFILE == \"release\" ]]; then terser $TRUNK_STAGING_DIR/*.js -o $TRUNK_STAGING_DIR/*.js --compress --mangle; fi"]

[[hooks]]
# Runs SSG on production builds
stage = "post_build"
command = "bash"
command_arguments = ["-c", "if [[ $TRUNK_PROFILE == \"release\" ]]; then cargo run --release --features ssg -- $TRUNK_STAGING_DIR; fi"]
