[build]
target = "index.html"
dist = "dist"

[tools]
wasm_opt = "version_110"

[[hooks]]
# Runs terser on the generated javascript glue-code
stage = "post_build"
command = "sh"
command_arguments = ["-c", "if [[ $TRUNK_PROFILE == \"release\" ]]; then terser $TRUNK_STAGING_DIR/*.js -o $TRUNK_STAGING_DIR/*.js --compress --mangle; fi"]